apiVersion: v1
kind: Service
metadata:
  labels:
    app: start
    app.kubernetes.io/instance: start
  name: start
  namespace: start-dev
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: start
  sessionAffinity: None
  type: ClusterIP
