apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
  namespace: tekton-pipelines
spec:
  storageClassName: gp2
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce