apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: start
  name: start
  namespace: start-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: start
  strategy: {}
  template:
    metadata:
      labels:
        app: start
    spec:
      containers:
      - image: eduardoriveror/start-image:v0.1
        name: start-image
        resources: {}
status: {}